import { FileText } from "lucide-react"
import Footer from "@/components/footer"
import Link from "next/link"

export const metadata = {
  title: "Terms & Conditions – Kleats",
  description: "Terms of use for the Kleats platform.",
}

export default function TermsPage() {
  return (
    <main className="min-h-screen page-transition">
      {/* Sticky Header aligned with app */}
      <div className="sticky top-0 z-10 bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60 border-b">
        <div className="container px-4 py-4 md:py-6">
          {/* Mobile Layout - Stacked */}
          <div className="md:hidden space-y-3">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-sm text-primary hover:underline transition-colors whitespace-nowrap"
            >
              ← Back to Home
            </Link>
            <div className="flex items-center justify-center gap-3">
              <div className="h-9 w-9 rounded-full bg-primary/10 text-primary flex items-center justify-center">
                <FileText className="h-5 w-5" />
              </div>
              <div>
                <h1 className="text-xl font-semibold leading-tight">Terms & Conditions</h1>
                <p className="text-xs text-muted-foreground">Last updated: August 20, 2025</p>
              </div>
            </div>
          </div>
          
          {/* Desktop Layout - Side by side */}
          <div className="hidden md:flex items-center">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-sm text-primary hover:underline transition-colors whitespace-nowrap px-3 py-2 cursor-pointer"
            >
              ← Back to Home
            </Link>
            <div className="flex-1 flex items-center justify-center gap-3">
              <div className="h-9 w-9 rounded-full bg-primary/10 text-primary flex items-center justify-center">
                <FileText className="h-5 w-5" />
              </div>
              <div>
                <h1 className="text-xl font-semibold leading-tight">Terms & Conditions</h1>
                <p className="text-xs text-muted-foreground">Last updated: August 20, 2025</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <section className="container px-4 py-8">
        <div className="mx-auto max-w-3xl">
          <div className="rounded-xl border bg-card text-card-foreground shadow-sm">
            <div className="p-6 md:p-8 space-y-6 text-sm leading-7 text-muted-foreground">
              <h2 className="text-base font-semibold text-foreground">1. Terms & Conditions</h2>
              <p>
                This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder
                as applicable and the amended provisions pertaining to electronic records in various statutes as amended by
                the Information Technology Act, 2000. This electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </p>
              <p>
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
                (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy
                and Terms of Use for access or usage of domain name kleats.in ("Website"), including the related mobile
                site and mobile application (hereinafter referred to as "Platform").
              </p>
              <p>
                The Platform is owned by EQUITECH LAB PRIVATE LIMITED, a company incorporated under the Companies Act, 1956
                with its registered office at Sai Residency, Pedavadlapudi, Guntur- 522302, Andhra Pradesh, Guntur, India
                (hereinafter referred to as "Platform Owner", "we", "us", "our").
              </p>
              <p>
                Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms
                of Use") as applicable to the Platform, including the applicable policies which are incorporated herein by
                way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable
                to the Platform for such transaction.
              </p>
              <p>
                By mere use of the Platform, you shall be contracting with the Platform Owner and these terms and conditions,
                including the policies, constitute your binding obligations with the Platform Owner.
              </p>
              <p>
                These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable)
                (collectively, "Services"). Any terms and conditions proposed by you which are in addition to, or which
                conflict with, these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or
                effect. These Terms of Use can be modified at any time without assigning any reason. It is your
                responsibility to periodically review these Terms of Use to stay informed of updates.
              </p>
              <p>
                For the purpose of these Terms of Use, wherever the context so requires, "you", "your" or "user" shall
                mean any natural or legal person who has agreed to become a user/buyer on the Platform.
              </p>
              <p className="uppercase tracking-wide text-foreground font-semibold">
                Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and
                conditions under these Terms of Use, so please read the Terms of Use carefully before proceeding.
              </p>
              <div>
                <p className="mb-2 text-foreground font-medium">
                  The use of Platform and/or availing of our Services is subject to the following Terms of Use:
                </p>
                <ul className="list-disc pl-5 space-y-2">
                  <li>You agree to provide true, accurate, and complete information during and after registration.</li>
                  <li>
                    We do not provide any warranty or guarantee as to the accuracy, timeliness, completeness, or
                    suitability of the information/materials.
                  </li>
                  <li>Use of our Services and Platform is at your own risk.</li>
                  <li>Unauthorized use of the Platform and/or Services may lead to action.</li>
                  <li>You agree to pay the charges associated with availing the Services.</li>
                  <li>You agree not to use the Platform for unlawful or illegal activities.</li>
                  <li>
                    Links to third-party websites are governed by their respective terms and privacy policies.
                  </li>
                  <li>
                    By initiating a transaction, you are entering into a legally binding and enforceable contract.
                  </li>
                  <li>
                    You shall indemnify and hold harmless the Platform Owner, its affiliates, officers, directors, and
                    employees against claims arising from your breach of Terms.
                  </li>
                  <li>
                    Neither party shall be liable for failure to perform obligations if prevented by a force majeure event.
                  </li>
                  <li>
                    These Terms shall be governed by the laws of India, and disputes shall be subject to the exclusive
                    jurisdiction of courts in Guntur, Andhra Pradesh.
                  </li>
                  <li>
                    For communication relating to these Terms, please use the contact details provided on the website.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}
